# config/config.yaml

models:
  input_shape: [256, 256, 3]

training:
  epochs: 200
  batch_size: 8
  learning_rate: 1e-4
  optimizer: Adam
  loss: mae
  metrics:
    - mae
  validation_split: 0.1
  save_best_only: true
  model_save_path: ./saved_models/advanced_model.keras
  final_model_save_path: ./saved_models/advanced_model_final.keras
  lr_reduce_factor: 0.5
  lr_reduce_patience: 10
  min_lr: 1e-6
  early_stop_patience: 20
  mixed_precision: false  # Mixed Precision'ı etkinleştirmek için true yapın

data:
  dataset_path: /Users/berkegulacar/Downloads/deblurganv3/GOPRO_Large/
  img_size: [256, 256]
  buffer_size: 1000
  num_parallel_calls: AUTOTUNE

logging:
  tensorboard_log_dir: ./logs/fit/
